<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="<?php echo $this->basePath('public/assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css') ?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath('public/assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css') ?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath('public/assets/global/plugins/clockface/css/clockface.css') ?>" rel="stylesheet" type="text/css" />


<?php if ($success == true): ?>
    <div class="custom-alerts alert alert-success fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button> Agendamento adicionado com sucesso
    </div>
    <script>
       setTimeout("$('#modal-agendamento').modal('hide');",2000);
    </script>
<?php endif; ?>

<?php
$this->formElementErrors()
        ->setMessageOpenFormat('<p class="text-danger">')
        ->setMessageSeparatorString('</br>')
        ->setMessageCloseString('</p>')
        ->render($formAgendamento);
?>

<form id="form" method="post" action="">
    <div class="form-body">
        <label>Nome do Cliente</label>
        <div class="input-group">
            <?php echo $this->formRow($formAgendamento->get('nomeCliente')) ?>
            <span class="input-group-addon">
                <i class="fa fa-user"></i>
            </span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <label>Data inicial</label>
                    <div class="input-group date form_datetime">
                        <?php echo $this->formRow($formAgendamento->get('dataInicial')) ?>
                        <span class="input-group-btn">
                            <button class="btn default date-set" type="button" style="height: 140%;">
                                <i class="fa fa-calendar"></i>
                            </button>
                        </span>
                    </div>
                </div>
                <div class="col-md-6">
                    <label>Data final</label>
                    <div class="input-group date form_datetime">
                        <?php echo $this->formRow($formAgendamento->get('dataFinal')) ?>
                        <span class="input-group-btn">
                            <button class="btn default date-set" type="button" style="height: 140%;">
                                <i class="fa fa-calendar"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="button" class="btn blue" onclick="submitAgendamento($(this));">Salvar Agendamento</button>
            <button type="button" class="btn dark btn-outline" data-dismiss="modal">Cancelar</button>
        </div>
    </div>
</form>


<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $this->basePath('public/assets/global/plugins/bootstrap-daterangepicker/moment.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('public/assets/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('public/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('public/assets/global/plugins/clockface/js/clockface.js'); ?>" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="<?php echo $this->basePath('public/assets/global/scripts/app.min.js'); ?>" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->basePath('public/assets/pages/scripts/components-date-time-pickers.min.js'); ?>" type="text/javascript"></script>