<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css') ?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css') ?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath('assets/global/plugins/clockface/css/clockface.css') ?>" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->

<?php
$this->formElementErrors()
        ->setMessageOpenFormat('<p class="text-danger">')
        ->setMessageSeparatorString('</br>')
        ->setMessageCloseString('</p>')
        ->render($formAgendamento);
?>
<form method="post" action="">
    <div class="modal-body">
        <div clas="row">
            <div class="col-md-8" style="float: none;">
                <?php if ($success): ?>
                    <div class="alert alert-success">
                        <strong>Sucesso!</strong> Agendamento criado com sucesso. 
                    </div>
                <?php endif; ?>

                <div class="form-body">
                    <label>Nome do Cliente</label>
                    <div class="input-group">
                        <?php echo $this->formRow($formAgendamento->get('nomeCliente')) ?>
                        <span class="input-group-addon">
                            <i class="fa fa-user"></i>
                        </span>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Data inicial</label>
                                <div class="input-group date form_datetime">
                                    <?php echo $this->formRow($formAgendamento->get('dataInicial')) ?>
                                    <span class="input-group-btn">
                                        <button class="btn default date-set" type="button" style="height: 140%;">
                                            <i class="fa fa-calendar"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Data final</label>
                                <div class="input-group date form_datetime">
                                    <?php echo $this->formRow($formAgendamento->get('dataFinal')) ?>
                                    <span class="input-group-btn">
                                        <button class="btn default date-set" type="button" style="height: 140%;">
                                            <i class="fa fa-calendar"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <?php echo $this->formRow($formAgendamento->get('submit')) ?>
        <button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>
    </div>
</form>

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/moment.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/clockface/js/clockface.js'); ?>" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->basePath('assets/pages/scripts/components-date-time-pickers.min.js'); ?>" type="text/javascript"></script>