<?php  echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php  echo $this->headTitle($this->translate('Kubano Ink Tattoo'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php  echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php  echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/public/css/style.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/layouts/layout/css/custom.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/layouts/layout/css/themes/darkblue.min.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/layouts/layout/css/layout.min.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/global/css/plugins.min.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/global/css/components.min.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/global/plugins/uniform/css/uniform.default.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/global/plugins/bootstrap/css/bootstrap.min.css')                        
                        ->prependStylesheet($this->basePath() . '/public/assets/global/plugins/simple-line-icons/simple-line-icons.min.css')
                        ->prependStylesheet($this->basePath() . '/public/assets/global/plugins/font-awesome/css/font-awesome.min.css')
                        //->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all')
        ?>

        <!-- Scripts -->
        <?php  echo $this->headScript()
            
            ->prependFile($this->basePath() . '/public/assets/global/plugins/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/public/assets/global/plugins/js.cookie.min.js')
            ->prependFile($this->basePath() . '/public/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js')
            ->prependFile($this->basePath() . '/public/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')
            ->prependFile($this->basePath() . '/public/assets/global/plugins/jquery.blockui.min.js')
            ->prependFile($this->basePath() . '/public/assets/global/plugins/uniform/jquery.uniform.min.js')
            ->prependFile($this->basePath() . '/public/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js')
            ->prependFile($this->basePath() . '/public/assets/pages/scripts/form-samples.min.js')
            ->prependFile($this->basePath() . '/public/assets/layouts/layout/scripts/layout.min.js')
            ->prependFile($this->basePath() . '/public/assets/layouts/layout/scripts/demo.min.js')
            ->prependFile($this->basePath() . '/public/assets/layouts/global/scripts/quick-sidebar.min.js')
            ->prependFile($this->basePath() . '/public/assets/global/scripts/app.min.js')
            ->prependFile($this->basePath() . '/public/assets/global/plugins/jquery.min.js')
        ; ?>
    </head>
    <body class=" login">
        <!-- BEGIN LOGO -->
        <div class="logo">
            <a href="index.html">
                <img src="<?php echo $this->basePath()?>/public/assets/pages/img/logo-big.png" alt=""> </a>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
            <form class="login-form" action="index.html" method="post" novalidate="novalidate">
                <h3 class="form-title font-green">Sign In</h3>
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button>
                    <span> Enter any username and password. </span>
                </div>
                <div class="form-group">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <label class="control-label visible-ie8 visible-ie9">Username</label>
                    <input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username"> </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Password</label>
                    <input class="form-control form-control-solid placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password"> </div>
                <div class="form-actions">
                    <button type="submit" class="btn green uppercase">Login</button>
                    <label class="rememberme check mt-checkbox mt-checkbox-outline">
                        <input type="checkbox" name="remember" value="1">Remember
                        <span></span>
                    </label>
                    <a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a>
                </div>
                <div class="login-options">
                    <h4>Or login with</h4>
                    <ul class="social-icons">
                        <li>
                            <a class="social-icon-color facebook" data-original-title="facebook" href="javascript:;"></a>
                        </li>
                        <li>
                            <a class="social-icon-color twitter" data-original-title="Twitter" href="javascript:;"></a>
                        </li>
                        <li>
                            <a class="social-icon-color googleplus" data-original-title="Goole Plus" href="javascript:;"></a>
                        </li>
                        <li>
                            <a class="social-icon-color linkedin" data-original-title="Linkedin" href="javascript:;"></a>
                        </li>
                    </ul>
                </div>
                <div class="create-account">
                    <p>
                        <a href="javascript:;" id="register-btn" class="uppercase">Create an account</a>
                    </p>
                </div>
            </form>
    </body>
</html>