<?php  echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php  echo $this->headTitle($this->translate('Kubano Ink Tattoo'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php  echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php  echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        
                        
                        ->prependStylesheet($this->basePath() . '/assets/pages/css/login.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/layouts/layout/css/custom.css')
                        ->prependStylesheet($this->basePath() . '/assets/layouts/layout/css/themes/darkblue.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/layouts/layout/css/layout.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/global/css/plugins.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/global/css/components.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/global/plugins/uniform/css/uniform.default.css')
                        ->prependStylesheet($this->basePath() . '/assets/global/plugins/bootstrap/css/bootstrap.min.css')                        
                        ->prependStylesheet($this->basePath() . '/assets/global/plugins/simple-line-icons/simple-line-icons.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/global/plugins/font-awesome/css/font-awesome.min.css')
                        //->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all')
        ?>

        <!-- Scripts -->
        <?php  echo $this->headScript()
            
            ->prependFile($this->basePath() . '/assets/global/plugins/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/global/plugins/js.cookie.min.js')
            ->prependFile($this->basePath() . '/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js')
            ->prependFile($this->basePath() . '/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')
            ->prependFile($this->basePath() . '/assets/global/plugins/jquery.blockui.min.js')
            ->prependFile($this->basePath() . '/assets/global/plugins/uniform/jquery.uniform.min.js')
            ->prependFile($this->basePath() . '/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js')
            ->prependFile($this->basePath() . '/assets/pages/scripts/form-samples.min.js')
            ->prependFile($this->basePath() . '/assets/layouts/layout/scripts/layout.min.js')
            ->prependFile($this->basePath() . '/assets/layouts/layout/scripts/demo.min.js')
            ->prependFile($this->basePath() . '/assets/layouts/global/scripts/quick-sidebar.min.js')
            ->prependFile($this->basePath() . '/assets/global/scripts/app.min.js')
            ->prependFile($this->basePath() . '/assets/global/plugins/jquery.min.js')
        ; ?>
    </head>
    <body class=" login">
        <!-- BEGIN LOGO -->
        <div class="logo">
            <a href="index.html">
                <img src="<?php echo $this->basePath('img/logo.png') ?>" alt=""> </a>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
            <form class="login-form" action="<?php echo $this->url('login')?>" method="post" novalidate="novalidate">
                <h3 class="form-title font-green">Logar</h3>
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button>
                    <span> Entre com usuário e senha </span>
                </div>
                <div class="form-group">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <label class="control-label visible-ie8 visible-ie9">Usuário</label>
                    <input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username"> </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Senha</label>
                    <input class="form-control form-control-solid placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password"> </div>
                <div class="form-actions">
                    <button type="submit" class="btn green uppercase">Login</button>                   
                </div>
                <?php if(isset($success)): ?>
                    <div class="note note-success">
                        <h3>Bootstrap Switch</h3>
                        <p><?php echo $success ?></p>
                    </div>
                <?php endif; ?>
            </form>
    </body>
</html>