 <h3>DESPESAS DO MES</h3>
        <table class="table table-bordered table-striped table-condensed flip-content">
            <thead class="flip-content">
                <tr>
                    <th width="20%"> Id </th>
                    <th> Custo </th>
                    <th> Valor</th>
                    <th> Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($caixas as $values): ?>
                    <?php if($values['tipoCaixa'] == 1) :?>
                            <tr>
                                <td><?php echo $values['idCaixa']; ?></td>
                                <td><?php echo $values['caixa']; ?></td>
                                <td><?php echo $values['valor']; ?></td>
                                <td> <a class="btn red" href="<?php echo $this->url('caixa', array('action'=>'edit','id'=>$values['idCaixa']))?>">Editar</a></td>
                            </tr>
                            <?php $totalDespesas += $values['valor'];?>
                    <?php endif; ?>
                <?php endforeach; ?>

                    <tr>
                        <td>Valor total das despesas</td>
                        <td></td>
                        <td><?php echo $totalDespesas; ?>,00</td>
                        <td></td>
                    </tr>
            </tbody>
        </table>

        <h3>CRÉDITOS DO MES </h3>
        <table class="table table-bordered table-striped table-condensed flip-content">
            <thead class="flip-content">
                <tr>
                    <th width="20%"> Id </th>
                    <th> Custo </th>
                    <th> Valor</th>
                    <th> Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($caixas as $values): ?>
                    <?php if($values['tipoCaixa'] == 2) :?>
                            <tr>
                                <td><?php echo $values['idCaixa']; ?></td>
                                <td><?php echo $values['caixa']; ?></td>
                                <td><?php echo $values['valor']; ?></td>
                                <td> <a class="btn red" href="<?php echo $this->url('caixa', array('action'=>'edit','id'=>$values['idCaixa']))?>">Editar</a></td>
                            </tr>
                            <?php $totalCredito += $values['valor'];?>
                    <?php endif; ?>
                <?php endforeach; ?>
                    <tr>
                        <td>Valor total creditado</td>
                        <td></td>
                        <td><?php echo $totalCredito; ?>,00</td>
                        <td></td>
                    </tr>
            </tbody>
        </table>

        <h3>RESUMO MENSAL</h3>
        <table class="table table-bordered table-striped table-condensed flip-content">
            <thead class="flip-content">
                <tr>
                    <th> Valor Total Credito </th>
                    <th> Valor Total Despesa</th>
                    <th> Resumo </th>
                </tr>
            </thead>
            <tbody>

                    <tr>
                        <td><?php echo $totalCredito; ?>,00</td>
                        <td><?php echo $totalDespesas; ?>,00</td>
                        <td <?php echo (($totalCredito - $totalDespesas) >= 0)?'style="color:green;"':'style="color:red;"' ?>><?php echo $totalCredito - $totalDespesas; ?>,00</td>
                    </tr>
            </tbody>
        </table>